# Generated by Django 4.2.5 on 2023-11-01 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_category_slug_alter_movie_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['time_create', 'title'], 'verbose_name': 'Найкращі статті', 'verbose_name_plural': 'Найкращі статі'},
        ),
    ]
